language: php

before_script: curl http://phpdoc.org/phpDocumentor.phar --output ./phpdoc.phar

script: php ./phpdoc.phar -d ./php/classes -t ./docs

deploy:
- provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: "./docs/"
  skip-cleanup: true
  on:
    branch: master